### ISSUE TITLE
Prepare "UI Designs" sub-page

### ISSUE THREAD

**Issue by hawelkam** [hawelkam/pb_portfolio_website#2]
Prepare the page according to the XD specs.

**Comment by bilu337** [comment]
Here are links to interactive pages:

**Furniture::** https://xd.adobe.com/view/1bd7099d-6696-410e-4340-ef6efdf3413b-6de6/
**Toxo Doctor Appointment:** https://xd.adobe.com/view/3784a222-dc0d-4f53-71f0-d86ad6bf9f4b-41b5/
**Bike App:** https://xd.adobe.com/view/e53e5cc1-ad79-40fa-60aa-4c41cd1ff3a5-930f/
**Adopt a plant website:** https://xd.adobe.com/view/4dbb2262-abb1-4c66-6a38-83c68f6f3eba-3b8a/
