### ISSUE TITLE
Fixing Testimonials

### ISSUE THREAD

**Issue by bilu337** [hawelkam/pb_portfolio_website#4]
1. Adding actual testimonials
2. Alligning "What People Say" to match the testimonials
3. Michał Hawełka testimonial must be written :P

**Comment by hawelkam** [comment]
@bilu337 Where are the actual testimonials? :D

**Comment by bilu337** [comment]
**Dr. Magdalena Majewska / Urban Vegan Owner**

Piotr Bilik has been working in our company since 2016. He immediately became known as a perfectly organized, punctual and conscientious person. 
Piotr's commitment allowed him to soon improve the graphic design of many components of our online store and visibility of our online store in social media. He is effective in action, concrete and factual, he is able to quickly and precisely assess the needs of a potential recipient. His creativity, organizational skills and ability to act efficiently in stressful situations have always been a guarantee of reliable work. Piotr's interpersonal skills have proven themselves in contacts with co-workers and clients. Many projects were created from scratch by Piotr together with the right colour strategy and met with the friendly reception of the shop's customers. Attention to detail, excellent workmanship and punctuality are just some of the many positive aspects of our cooperation.

**Anna Bilik / Mom**

The best person in the world

**Michał Hawek / _Web Developer?_**

To be written
